INSERT INTO dept VALUES (50, 'INFORMÀTICA', 'SINEU');

INSERT INTO dept VALUES (60, 'COMPRES', 'MANACOR');

INSERT INTO dept VALUES (70, 'PERSONAL', 'INCA');

INSERT INTO dept VALUES (80, 'SERVEIS MÈDICS', '');

INSERT INTO EMP VALUES (7935,'GOTERA','PSICÒLEG',7839, '1981-11-09', 390000,NULL,80);


UPDATE dept 
set `LOC`='VALENCIA'
where `DEPT_NO`=80